---
# tasks file for k8s_installation

- name: copy the k8s repository file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/

- name: update yum repository and packages
  yum:
    name: '*'
    state: latest
 
- name: installing kubernetes
  yum:
    name: ['kubelet', 'kubeadm', 'kubectl', 'docker', 'python2-pip', 'libselinux-python']
    enablerepo: kubernetes
    state: present

- name: enabling and starting kubelet and docker service 
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: 
    - docker
    - kubelet

- name: disabling selinux status
  selinux:
    state: disabled

- name: disabling swap
  command: 'swapoff -a'

- name: initiating kubernetes master using kubeadm 
  command: kubeadm init

- name: create the .kube directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - $HOME/.kube
    - '"{{ playbook_dir }}"/group_vars'
- name: copy configuration file from /etc/kubernetes/admin.conf
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: $HOME/.kube/config

- name: changing ownership
  file:
    owner: root
    group: root
    path: $HOME/.kube/config

- name: restart kubelet service 
  service:
    name: kubelet
    state: restarted
 
- name: getting kubeadm join token 
  command: 'kubeadm token create --print-join-command'
  register: kubeadm_join_command

- name: save the kubeadm command for later use 
  copy:
    content: "{{ kubeadm_join_command }}"
    dest: '"{{ playbook_dir }}"/group_vars/all'


