---
# tasks file for k8s_installation

- name: copy the k8s repository file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/

- name: update yum repository and packages
  yum:
    name: '*'
    state: latest
 
- name: installing kubernetes
  yum:
    name: ['kubelet', 'kubeadm', 'kubectl', 'docker', 'python2-pip', 'libselinux-python']
    enablerepo: kubernetes
    state: present

- name: enabling and starting kubelet and docker service 
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: 
    - docker
    - kubelet

- name: disabling selinux status
  selinux:
    state: disabled

- name: disabling swap
  command: 'swapoff -a'

- name: initiating kubernetes master using kubeadm 
  command: kubeadm init

- name: create the .kube directory
  file:
    path: $HOME/.kube
    state: directory

- name: copy configuration file from /etc/kubernetes/admin.conf
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: $HOME/.kube/config

- name: changing ownership
  file:
    owner: root
    group: root
    path: $HOME/.kube/config

- name: restart kubelet service 
  service:
    name: kubelet
    state: restarted
 
- name: getting kubeadm join token 
  command: 'kubeadm token list -o json'
  register: kubeadm_token

- debug:
    msg: "{{ kubeadm_token.stdout_lines[0].token }}"
